workflows: 
    android-workflow:
      name: Android workflow

      environment: 
        flutter: stable
      
      scripts:
        - flutter clean
        - flutter pub get
        - flutter build apk --release

      artifacts:
        - build/**/outputs/**/*.apk
        
      